//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstituteofFineArts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<int> TopicId { get; set; }
        public Nullable<int> Point { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Student Student { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
